name: Synchronisation Airtable vers Sellsy

on:
  schedule:
    # Exécution toutes les 3 heures
    - cron: '0 */3 * * *'
  workflow_dispatch:  # Déclenchement manuel possible

jobs:
  synchronisation-clients:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configurer Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Exécuter le Script de Synchronisation
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
        SELLSY_CONSUMER_TOKEN: ${{ secrets.SELLSY_CONSUMER_TOKEN }}
        SELLSY_CONSUMER_SECRET: ${{ secrets.SELLSY_CONSUMER_SECRET }}
        SELLSY_USER_TOKEN: ${{ secrets.SELLSY_USER_TOKEN }}
        SELLSY_USER_SECRET: ${{ secrets.SELLSY_USER_SECRET }}
      run: |
        python sellsy_sync_script.py
