name: Sync Airtable Clients to Sellsy V2

on:
  schedule:
    - cron: '0 */3 * * *'  # Toutes les 3 heures
  workflow_dispatch:  # Permet aussi de lancer manuellement depuis GitHub

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Initialize Sellsy OAuth2 tokens
        run: |
          python init_sellsy_tokens.py --client_id "${{ secrets.SELLSY_CLIENT_ID }}" --client_secret "${{ secrets.SELLSY_CLIENT_SECRET }}" --update_env
        
      - name: Run client sync script
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
          SELLSY_CLIENT_ID: ${{ secrets.SELLSY_CLIENT_ID }}
          SELLSY_CLIENT_SECRET: ${{ secrets.SELLSY_CLIENT_SECRET }}
        run: python main.py
